### ISSUE TITLE
Should this repo be deprecated?

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/bigquery-getting-started-python#14]
Because we have identical samples in (java|python)-docs-samples?

**Comment by theacodes** [comment]
If they are identical, then yes, please let's deprecate @elibixby.

**Comment by elibixby** [comment]
Yes should be deprecated

I think we were waiting for java-docs-samples to be updated, but if we're satisfied with that lets deprecate

**Comment by elibixby** [comment]
Changed README waiting on Will to move
